GOOGLE_APP_ID: "1093393924993-tu6b0v8ikmj2nah94ijr0v2qdvaptjhr.apps.googleusercontent.com"
GOOGLE_APP_SECRET: "Gefmg_0ZQAcYOeM6eNDApTa-"

FACEBOOK_APP_ID: "161631281206243"
FACEBOOK_APP_SECRET: "a60b2fe12182cbab429eeac1501b6b8b"

TWITTER_API_KEY: "WYTKseybfwgSFAZA1gk0Xm5vg"
TWITTER_API_SECRET: "KD0XpiQc6ewI0OYpzkof7XJc4WdarQzrbUBroTRFOdOUWUgOJe"
